name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Clean and build with Maven
      run: mvn clean package --file zero/pom.xml

    - name: Get project version
      id: get_version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file zero/pom.xml)" >> $GITHUB_ENV

    - name: List target directory
      run: ls -la zero/target

    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: zero-latest
        path: zero/target/zero-${{ env.VERSION }}.jar

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -f zero/pom.xml deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
