name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Clean and build with Maven
      run: mvn clean package --file zero/pom.xml

    - name: List target directory
      run: ls -la zero/target

    - name: Upload JAR file to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: zero/target/*.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        body: "Release of version ${{ github.event.release.tag_name }}"
        draft: false
        prerelease: false
