name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file zero/pom.xml

    - name: List target directory
      run: ls -la zero/target

    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: my-jar-file
        path: zero/target/*.jar

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -f zero/pom.xml deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
